apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: boce-wac-project-ambulance-ufe
spec:
  module-uri: http://boce-wac-project-ambulance-ufe.wac-hospital/build/boce-wac-project-ambulance-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: boce-wac-project-login    # element, ktorý bude vložený na stránku
      attributes:
      - name: api-base
        value: http://localhost:30081/api
      path: boce-wac-project      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Projekt WAC Boris Černák      # názov mikro aplikácie
      details: Portál pre pacientov kde môžu získať prehľad o svojich chorobách, uskutočnéných a plánovaných návštevách ambulancie.
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach