apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: boriscernak/boce-wac-project-ambulance-ufe
  newName: boriscernak/boce-wac-project-ambulance-ufe
  newTag: 1.0.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: boriscernak/boce-wac-project-ambulance-wl-webapi
  newName: boriscernak/boce-wac-project-ambulance-wl-webapi
  newTag: 1.1.0  

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: boce-wac-project-ambulance-ufe
     fieldPaths:
         - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  boce-wac-project-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1