apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: boce-wac-project-cd # v spoločnom klastri je nasadených viacero takýchto objektov
    namespace: wac-hospital
spec:
    wait: true
    interval: 42s
    path: clusters/wac-aks
    prune: true
    sourceRef:
        kind: GitRepository
        name: boce-wac-project-gitops-repo