kind: Service
apiVersion: v1
metadata:
  name: boce-wac-project-openapi-ui
spec:
  selector:
    pod: boce-wac-project-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081